# Playbook for Ansible Windows workshop setup.  
---
- name: Provision EC2 Instances
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars/main.yml
  tags: 
    - manage-ec2-instances
  roles:
    - manage-ec2-instances
 
# Configure Active Directory 
- name: Configure Active Directory Domain Controller
  hosts: windows_domain_controllers
  gather_facts: no
  vars_files:
    - vars/main.yml
  tags: 
    - windows-ad-controller
  roles:
    - windows-ad-controller

# Configure Workstation host 
- name: Configure Windows Workstation
  hosts: windows_workstations
  vars_files:
    - vars/main.yml
  gather_facts: True
  tags:
    - windows-workstation
  roles:
    - windows-common
    - windows-workstation

# Configure Tower host
- name: Configure Ansible Host 
  hosts: tower
  become: True
  remote_user: ec2-user
  gather_facts: True
  vars_files:
    - vars/main.yml
  tags:
    - ansible-tower
  roles: 
    - ansible-tower

# Configure Windows Hosts
- name: Configure Windows Servers
  hosts: windows
  gather_facts: True
  vars_files:
    - vars/main.yml
  tags: 
    - windows_hosts
  roles: 
    - windows-common

# Configure GitLab Host
- name: Configure GitLab Host
  hosts: gitlab
  become: True
  remote_user: ec2-user
  gather_facts: True
  vars_files:
    - vars/main.yml
  tags:
    - gitlab
  roles:
    - { role: linux-common }
    - { role: geerlingguy.gitlab }

# Run post-config separate to avoid handler restart issue...
- name: Gitlab Post Config
  hosts: gitlab
  become: True
  remote_user: ec2-user
  gather_facts: True
  vars_files:
    - vars/main.yml
  tags:
    - gitlab
  roles:
    - { role: gitlab-postconfig }




